apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-appppppp
  labels:
    app: swiggy-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-app
        image: vishnu155/icerems:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
